<?
    function get_productList()
    {
        return array(
            'Albatross Ocean King T-shirt',
            'Albatross Ocean King Top',
            'Anarchy Hoody',
            'Anarchy T-shirt',
            'Astronaut T-Shirt',
            'Plain Bamboo Top - 3 Pack',
            'Bamboo Whale Love Top',
            'Baseball Jersey',
            'Be The Change T-shirt',
            'Be The Change Top',
            'Beach Bum Jumper',
            'Beach Bum Top',
            'Beach Bum Vest Top',
            'Bear Cycling T-Shirt',
            'Bear Hoody',
            'Bear Jumper',
            'Bear Necessities T-shirt',
            'Bear Necessities Top',
            'Bear Sweatshirt',
            'Bear T-shirt',
            'Bear Top',
            'Best Waves In Life T-shirt',
            'Boardies Not Borders T-shirt',
            'Boardies Not Borders Top',
            'Books Not Bombs T-shirt',
            'Books Not Bombs Top',
            'Born To Shred Crew Neck Tee',
            'Born To Shred T-shirt',
            'Cactus Hang Ten Baseball Tee',
            'Cactus Hang Ten T-shirt',
            'Cactus Hang Ten Top',
            'Camping Baseball Tee',
            'Camping Hoody',
            'Camping Jumper',
            'Camping Sweatshirt',
            'Camping T-shirt',
            'Climate Change T-Shirt',
            'Climate Change Top',
            'Custom Printed Peace Symbol T-Shirt',
            'Dawn Patrol Hoody',
            'Dawn Patrol T-shirt',
            'Dawn Patrol Top',
            'Drop Seeds Kid\'s T-shirt',
            'Drop Seeds Not Bombs T-Shirt',
            'Drop Seeds Womens Top',
            'Economy Top',
            'EJF Bee T-shirt',
            'EJF Bee Vest Top',
            'Elephant Top',
            'Ethical Fast Fashion Top',
            'Fukushima Skate Park Jumper',
            'Fukushima Skate Park T-shirt',
            'Galaxy T-Shirt',
            'Give Peace A Chance T-shirt',
            'Give Peace A Chance Top',
            'Give Trees A Chance T-shirt',
            'Give Trees a Chance Top',
            'Globe T-shirt',
            'Gone Cleaning T-shirt',
            'Gone Cleaning Top',
            'Hammerhead Shark Bamboo Top',
            'Hammerhead Shark T-shirt',
            'Hammerhead Shark Top',
            'Heroes T-shirt',
            'Heroes Top',
            'Hope Beats Fear T-shirt',
            'Hope Beats Fear Top',
            'Human T-shirt',
            'Hummingbird Crew Neck Tee',
            'Hummingbird Hoody',
            'Hummingbird Sweatshirt',
            'Hummingbird T-shirt',
            'Hummingbird Top',
            'I Love Sharks T-shirt',
            'I Love Sharks Top',
            'I Love Wight T-Shirt',
            'International Rescue Pocket Badge T-Shirt',
            'International Rescue Pocket Badge Top',
            'Killer Whale T-shirt',
            'Killer Whale Top',
            'Kingfisher Crew Neck Tee',
            'Kingfisher Hoody',
            'Kingfisher Jumper',
            'Kingfisher T-shirt',
            'Kingfisher Top',
            'Know Hope Boyfriend Tee',
            'Know Hope T-shirt',
            'Know Hope Vest Top',
            'Kraken T-shirt',
            'Kraken Top',
            'Leaf Classic Organic T-Shirt',
            'Leave Only Footprints T-shirt',
            'Leave Only Footprints Top',
            'Let Us Go Forward Together T-shirt',
            'Lightning Bolt Hoody',
            'Lightning Bolt T-Shirt',
            'Lion Jumper',
            'Lion T-shirt',
            'Lion Top',
            'Logo Kid\'s Top',
            'Love Heart Bamboo Top',
            'Love Mini Mantas T-shirt',
            'Love Mini Mantas Top',
            'Love The Sea Top',
            'Make Do and Mend Top',
            'Marlin T-shirt',
            'Men\'s Adventure Bamboo Socks',
            'Men\'s Anchor Boxer Shorts',
            'Men\'s Aran British Wool Beanie',
            'Men\'s Nautical Bundle',
            'Men\'s Aran Merino Wool Jumper',
            'Men\'s Astronaut Bamboo Socks',
            'Men\'s Athletic Grey Boxer Shorts',
            'Men\'s Atlantic Merino Wool Jumper',
            'Men\'s Bamboo Socks',
            'Men\'s Rad Bamboo Socks - 3 Pack',
            'Men\'s Rad Bamboo Socks - 5 Pack',
            'Men\'s Rad Bamboo Socks - 7 Pack',
            'Men\'s Organic Baseball Jersey - 3 Pack',
            'Men\'s Beach Bamboo Socks',
            'Men\'s Black Bamboo Socks',
            'Men\'s Black Boxer Shorts',
            'Men\'s Black Organic Cotton Hoody',
            'Men\'s Black Organic Crew Neck Sweatshirt',
            'Men\'s Blue Flannel Shirt',
            'Men\'s Boxer Shorts - 7 Pack',
            'Men\'s Boxer Shorts - 3 Pack',
            'Men\'s Boxer Shorts - 5 Pack',
            'Men\'s British Wool Scarf',
            'Men\'s Brown Flannel Shirt',
            'Men\'s Cactus Bamboo Socks',
            'Men\'s Cactus Boxer Shorts',
            'Men\'s Dark Yellow Merino Wool Jumper',
            'Men\'s Denim Blue Zip Hoody',
            'Men\'s Disco Bamboo Socks',
            'Men\'s Disco Boxer Shorts',
            'Men\'s Fade Bamboo Socks',
            'Men\'s Fish Bamboo Socks',
            'Men\'s Free T-shirt Bundle',
            'Men\'s Coastal Bundle',
            'Men\'s Flannel Shirts & Plain T-shirt Bundle',
            'Men\'s Flannel Shirt Bundle',
            'Men\'s Flannel Shirt - 2 Pack',
            'Men\'s Green Check Flannel Shirt',
            'Men\'s Green Surf Towel Change Robe',
            'Men\'s Grey Bamboo Socks Pack',
            'Men\'s Grey Check Flannel Shirt',
            'Men\'s Grey Merino Wool Jumper',
            'Men\'s Herringbone Blue Flannel Shirt',
            'Men\'s Herringbone Grey Flannel Shirt',
            'Men\'s Light Heather Organic Cotton Hoody',
            'Men\'s Light Heather Organic Crew Neck Sweatshirt',
            'Men\'s Light Heather Zip Hoody',
            'Men\'s Lightning Bamboo Socks',
            'Men\'s Winter Warmer Bundle',
            'Men\'s Ultimate Bundle',
            'Men\'s Winter Wool Bundle',
            'Men\'s Navy Blue Organic Crew Neck Sweatshirt',
            'Men\'s Navy British Wool Beanie',
            'Men\'s Navy Merino Wool Jumper',
            'Men\'s Navy Organic Cotton Hoody',
            'Men\'s Organic Cotton Hoody - 2 Pack',
            'Men\'s Adventure Bundle',
            'Men\'s Lightning Bundle',
            'Men\'s Eco Warrior Bundle',
            'Men\'s Zip Hoody & Plain T-shirt Bundle',
            'Men\'s Zip Hoody & Baseball Jersey Bundle',
            'Men\'s Organic Zip Hoody - 2 Pack',
            'Men\'s Peace Bamboo Socks',
            'Men\'s Purple Flannel Shirt',
            'Men\'s Red Flannel Shirt',
            'Men\'s Red Merino Wool Jumper',
            'Men\'s Red Wine Organic Cotton Hoody',
            'Men\'s Red Wine Zip Hoody',
            'Men\'s Redwood Merino Wool Jumper',
            'Men\'s Sage Green Zip Hoody',
            'Men\'s Shark Bamboo Socks',
            'Men\'s Slate British Wool Beanie',
            'Men\'s Slate Merino Wool Jumper',
            'Men\'s Space Boxer Shorts',
            'Men\'s Stone Merino Wool Cardigan',
            'Men\'s Striped Bamboo Socks',
            'Men\'s Surf Bamboo Socks',
            'Men\'s Shred Bundle',
            'Men\'s Tobacco Merino Wool Cardigan',
            'Men\'s Tobacco Merino Wool Jumper',
            'Men\'s Weather Bamboo Socks',
            'Men\'s White Bamboo Socks',
            'Men\'s Yellow Surf Towel Change Robe',
            'Message In A Bottle T-shirt',
            'Message In A Bottle Top',
            'Microplastics Crew Neck Tee',
            'Microplastics Jumper',
            'Microplastics Sweatshirt',
            'Microplastics T-shirt',
            'No Limits Campaign T-shirt',
            'No Limits Campaign Top',
            'Ocean Hoody',
            'Ocean Hoody',
            'Ocean T-shirt',
            'Ocean Top',
            'Ocean Unite Hoody',
            'Ocean Unite T-shirt',
            'Ocean Unite Top',
            'Octopus Hoody',
            'Octopus Jumper',
            'Octopus Sweatshirt',
            'Octopus T-shirt',
            'Octopus Top',
            'One in 7bn T-shirt',
            'One in 7bn Top',
            'One Ocean T-shirt',
            'One Ocean Top',
            'Organic Cotton Top - 3 Pack',
            'Organic Cotton Top - 5 Pack',
            'Overpopulation T-Shirt',
            'Panther Jumper',
            'Panther Top',
            'Panther Women\'s Sweater',
            'Peace Symbol T-Shirt',
            'Plain Bamboo T-Shirt',
            'Plain Bamboo T-shirt - 3 Pack',
            'Plain Bamboo Top',
            'Organic Cotton T-shirt - 7 Pack',
            'Organic Cotton Top - 7 Pack',
            'Organic Cotton Polo - 2 Pack',
            'Plain Organic T-shirt',
            'Organic Cotton T-shirt - 3 Pack',
            'Organic Cotton T-shirt - 5 Pack',
            'Plain Women\'s Crew Neck Tee',
            'Plain Women\'s Organic Top',
            'Plain Women\'s Vest Top',
            'Planet B Boyfriend Tee',
            'Planet B T-shirt',
            'Planet B Vest Top',
            'Planet B Womens Bamboo Top',
            'Plastic Fish T-shirt',
            'Plastic Fish Top',
            'Plastic Ocean T-shirt',
            'Plastic Ocean Top',
            'Plastic Pollution T-shirt',
            'Plastic Pollution Top',
            'Plastic Project T-shirt',
            'Plastic Project Top',
            'Pocket Fin T-shirt',
            'Pocket Logo T-shirt',
            'Polar Bear Jumper',
            'Polar Bear Sweatshirt',
            'Polar Bear T-shirt',
            'Polar Bear Top',
            'Polar Berg Crew Neck Tee',
            'Polar Berg Hoody',
            'Polar Berg Jumper',
            'Polar Berg T-shirt',
            'Polar Berg Top',
            'Protect The Ocean Hoody',
            'Protect The Ocean Jumper',
            'Protect The Ocean T-shirt',
            'Protect The Ocean Top',
            'Pyramid T-Shirt',
            'Pyramid Top',
            'Rapanui Gift Voucher',
            'Rapanui Logo Bamboo T-shirt',
            'Rapanui Logo T-Shirt',
            'Rapanui Logo T-shirt (Dark Grey)',
            'Recession Bamboo T-Shirt',
            'Revolutions Bamboo T-Shirt',
            'Revolutions Jumper',
            'Safety Third Jumper',
            'Safety Third T-shirt',
            'Save our Seas Bamboo Top',
            'Save Our Seas Crew Neck Tee',
            'Save Our Seas Hoody',
            'Save Our Seas Jumper',
            'Save Our Seas Pullover Hoody',
            'Save Our Seas Sweatshirt',
            'Save Our Seas T-shirt',
            'Save Our Seas T-Shirt',
            'Save The Bumblebees T-shirt',
            'Save The Bumblebees Top',
            'Sea Level T-shirt',
            'Seas The Day Crew Neck Tee',
            'Seas The Day Hoody',
            'Seas The Day Sweatshirt',
            'Seas The Day T-shirt',
            'Sex Drugs & Beach Cleans Boyfriend Tee',
            'Shark Hoody',
            'Shark T-shirt',
            'Shark Top',
            'Skull & Bones Skater Tee',
            'Space Shuttle T-shirt',
            'Space Shuttle Womens Vest Top',
            'Stop Ivory Trade Now T-shirt',
            'Stop Ocean Plastic T-shirt',
            'Stop Ocean Plastic T-Shirt',
            'Stop Ocean Plastic Top',
            'Stop Ocean Plastic Top',
            'Straws Suck T-shirt',
            'Straws Suck Top',
            'Sun Jumper',
            'Sun T-shirt',
            'Sun Top',
            'Sun Vest Top',
            'Sunset Top',
            'Men\'s Surf Bundle',
            'Women\'s Surf\'s Up Bundle',
            'SURF Top',
            'Surfboard Baseball T-shirt',
            'Surfboard T-shirt',
            'Surfboard Top',
            'Surfboard Top',
            'Swallow Top',
            'Swell Lines T-Shirt',
            'Team Ocean Hoody',
            'Team Ocean Sweatshirt Women\'s',
            'Team Ocean T-shirt',
            'Team Ocean Top',
            'Tern Sweatshirt',
            'Tern T-shirt',
            'Tern Top',
            'The Ocean Cleanup T-shirt',
            'The Ocean Cleanup Top',
            'The Tree Tee (White)',
            'The Tree Top (White)',
            'Thunder Hoody',
            'Men\'s Bestsellers Bundle',
            'Thunder T-Shirt',
            'Thunderbird 1 T-Shirt',
            'Thunderbird 1 Top',
            'Thunderbird 2 T-Shirt',
            'Thunderbird 2 Top',
            'Thunderbird 3 T-Shirt',
            'Thunderbird 3 Top',
            'Thunderbird 4 T-Shirt',
            'Thunderbird 4 Top',
            'Thunderbird 5 T-Shirt',
            'Thunderbird 5 Top',
            'Thunderbirds Are Go T-Shirt',
            'Thunderbirds Are Go Top',
            'Thunderbirds Comic T-shirt',
            'Thunderbirds Comic Top',
            'Thunderbirds Pattern T-shirt',
            'Thunderbirds Pattern Top',
            'To The Sea T-Shirt',
            'Turbine Sweatshirt',
            'Turbine T-shirt',
            'Untapped Treasure Bamboo Top',
            'Untapped Treasure Crew Neck Tee',
            'Untapped Treasure T-Shirt',
            'Organic Cotton Vest Top - 3 Pack',
            'Virunga Emblem T-shirt',
            'Virunga Emblem Top',
            'Virunga Logo Crew Neck Tee',
            'Virunga Logo Jumper',
            'Virunga Logo Sweatshirt',
            'Virunga Logo T-shirt',
            'Vitamin Sea T-shirt',
            'Vivienne Westwood X War Child T-shirt',
            'Vivienne Westwood X War Child Top',
            'Watercolour Gorillas T-shirt',
            'Watercolour Gorillas Top',
            'Watercolour Tiger T-shirt',
            'Watercolour Tiger Top',
            'Wave Baseball Tee',
            'Wave T-shirt',
            'Wave Top',
            'Wolf Jumper',
            'Women\'s Aran British Wool Beanie',
            'Women\'s Aran British Wool Scarf',
            'Women\'s Aran Merino Wool Jumper',
            'Women\'s Bamboo Socks',
            'Women\'s Rad Bamboo Socks - 3 Pack',
            'Women\'s Rad Bamboo Socks - 5 Pack',
            'Women\'s Rad Bamboo Socks - 7 Pack',
            'Women\'s Baseball Jersey',
            'Women\'s Black Organic Jumper',
            'Women\'s Bumblebee Bamboo Socks',
            'Women\'s Crew Neck Tee - 3 Pack',
            'Women\'s Denim Blue Zip Hoody',
            'Women\'s Diamond Bamboo Socks',
            'Women\'s Flamingo Bamboo Socks',
            'Women\'s Ultimate Bundle',
            'Women\'s Winter Essentials Bundle',
            'Women\'s Flannel Shirt & Crew Neck Tee Bundle',
            'Women\'s Flannel Up Bundle',
            'Women\'s Fox Bamboo Socks',
            'Women\'s Green Check Flannel Shirt',
            'Women\'s Green Surf Towel Change Robe',
            'Women\'s Grey Check Flannel Shirt',
            'Women\'s Grey Merino Wool Jumper',
            'Women\'s Light Heather Organic Cotton Hoody',
            'Women\'s Light Heather Organic Jumper',
            'Women\'s Lightning Bolt Top',
            'Women\'s Winter Wool Bundle',
            'Women\'s Winter Warmer Bundle',
            'Women\'s Mustard Merino Wool Jumper',
            'Women\'s Navy British Wool Beanie',
            'Women\'s Navy Organic Cotton Hoody',
            'Women\'s Bee Bundle',
            'Women\'s Low Poly Bundle',
            'Women\'s Animal Bundle',
            'Women\'s Classics Bundle',
            'Women\'s Zip Hoody & Plain Top Bundle',
            'Women\'s Zip Hoody & Baseball Tee Bundle',
            'Women\'s Organic Zip Hoody - 2 Pack',
            'Women\'s Pastel Pink Bamboo Socks',
            'Women\'s Patterned Bamboo Socks',
            'Women\'s Peace Bamboo Socks',
            'Women\'s Organic Basics Bundle',
            'Women\'s Purple British Wool Scarf',
            'Women\'s Red Wine Zip Hoody',
            'Women\'s Sage Green Zip Hoody',
            'Women\'s Slate British Wool Beanie',
            'Women\'s Slate British Wool Scarf',
            'Women\'s Spotty Bamboo Socks',
            'Women\'s Stone Merino Wool Cardigan',
            'Women\'s Shred Bundle',
            'Women\'s Coastal Bundle',
            'Women\'s Yellow Surf Towel Change Robe',
        );
    }
?>